### ISSUE TITLE
TypeError when trying to convert cbr to cbz

### ISSUE THREAD

**Issue by rurickdev** [ajslater/comicbox#14]
running `comicbox -z --delete-rar COMIC_FILE.cbr` throws `TypeError: 'NoneType' object is not iterable`

also when trying to run with `--recurse` and changing the file to a directory it shows `{args.path}` is not a file and files with the same TypeError after that

![photo_2021-06-18 11 31 06](https://user-images.githubusercontent.com/6403537/122591547-b80c1180-d028-11eb-892f-21fe069cf519.jpeg)

![photo_2021-06-18 11 31 04](https://user-images.githubusercontent.com/6403537/122591527-b3475d80-d028-11eb-9159-f2d783d51bb1.jpeg)

**Comment by ajslater** [comment]
Fixed with v0.1.6
