### ISSUE TITLE
Example for writing metadata?

### ISSUE THREAD

**Issue by benausro** [ajslater/comicbox#15]
Hi,

could you maybe give an example how to add metadata to a cbz file? Thank you!

Ben

**Comment by ajslater** [comment]
comicbox was originally intended just to be a library for the comic reader [codex](/ajslater/codex/). As such, metadata writing is rudamentary and not available on the command line. Here's a simple programatic example from the test suite:

[/ajslater/comicbox/blob/master/tests/test_cix.py](/ajslater/comicbox/blob/master/tests/test_cix.py)

Practically, I recommend continuing to use [comictagger](https://github.com/comictagger/comictagger). There was an ambitious hope that comicbox might learn how to do everything comictagger does, but other concerns have prevented work on this project and I don't know if or when I shall return to it.
