### ISSUE TITLE
Import metadata fails

### ISSUE THREAD

**Issue by TweetyTV** [ajslater/comicbox#61]
I'm trying to import metadata into a cbz but whatever format I use I get the error below. Even if I export the existing metadata from the cbz and try to import it unchanged I get the same error. I also tried without a cbz, just to read the file, same error.
Whatever format I use (filenames as described in the readme: comicbox.yaml, comicinfo.xml,...) it's like it always falls back to FilenameSchema.

Edit: I'm using to new 1.0.0 version

``` bash
LOGLEVEL=DEBUG comicbox -i "comicbox-cli.yaml" -P d
2024-01-17 17:59:36 CET DEBUG    Parsed Imported File with FilenameSchema
2024-01-17 17:59:36 CET ERROR    None: Unable to normalize Imported File:None metadata
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/comicbox/box/normalize.py", line 19, in _normalize_metadata
    transform = transform_class(self._path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' obj
```

**Comment by ajslater** [comment]
Thanks for reporting this. This should be fixed in [verstion 1.1.0](https://github.com/ajslater/comicbox/releases/tag/v1.1.0)

And I've created an automated test to prevent regressions.
