### ISSUE TITLE
ComicInfo.xml naming and location issues

### ISSUE THREAD

**Issue by beville** [ajslater/comicbox#64]
I've been playing a little with comicbox as a CLI tool, and it's pretty sweet.

I did run into a few snags though, regarding the XML file naming and sub-folder location.  I'm not sure what the current standards (de-faco or otherwise) are, so it's not clear if they're bugs or not.

1. If I modify the metadata of a cbz file with comicbox it will replace the existing "ComicInfo.xml" file with one named "comicinfo.xml".  This is not recognized by ComicTagger app, so if I re-tag with that app, the zip then has both versions.
  example usage
   ```
   comicbox  "Whiz Comics #007 (1940).cbz"  -m "Publisher: Fawcett Pub" -w cr
   ```

2. comicbox is also flexible about finding ComicInfo.xml files in archive subfolders, which other apps might be ignoring.  Using comicbox to modify a file where the XML is at both "comicname 1/ComicInfo.xml" and root-level "ComicInfo.xml" might do some unexpected merging to a root-level "comicinfo.xml"

My own expectation was that the file should be at the archive root level and mixed case only.

The Anansi Project docs are quite good about defining the contents of the XML file, but seem silent, near as I can find, on the file naming and location.  

Testing with a few applications with different files: 
* one with a lower case "comicinfo.xml" at root level
* one with  "ComicInfo.xml" in a subfolder

*Don't* recognize the file:

* ComicTagger 
* Komga

*Do* recognize the file:
* Chunky
* Codex (of course!)

So, not really sure *what* the correct behavior should be.  I also mentioned this in a discussion on comictagger github (https://github.com/comictagger/comictagger/discussions/531)  Maybe this should be addressed instead over here: https://github.com/anansi-project/comicinfo/discussions

**Comment by ajslater** [comment]
Thanks for this. Interesting things to think about. At the very least, comicbox should write the file mixed case so comictagger doesn't ignore it. It will also be a little easier for humans to read.

**Comment by ajslater** [comment]
[Comicbox v1.1.1](https://github.com/ajslater/comicbox/releases/tag/v1.1.1) now writes ComicInfo.xml, MetronInfo.xml and CoMet.xml in TitleCase for the benefit of progams expecting that.

Comicbox continues to read metadata files in any case and from all locations in the archive directory tree.
