### ISSUE TITLE
Special characters in tags

### ISSUE THREAD

**Issue by nuclearedc** [ajslater/comicbox#67]
Hi,
How can special characters be added into text without conflicting with the code?

For example:
-m "Series: Battle Angel Alita: Last Order" 
It would give me an error resulting from the special character : in the name of the series.

-m "Summary: When Doc Ido, a talented cyber-physician, finds Gally's head in a junk heap..."
Only "When Doc Ido" will be saved into the summary field. The comma after the word Ido is what is creating the issue.

Thank you.

**Comment by ajslater** [comment]
What happens inside the quotes there is yaml parsing. YAML parsers will often try to assume things are strings when they can, but you can be explicit about it if you include yaml syntax in the string you're trying to insert.
So I think something like:
```sh
-m "Series: 'Battle Angel Alita: Last Order'"
```
might work with the single quotes.
and this might work with single quotes to the shell, but double quotes defining the string to yaml surrounding the lone single quote.
```sh
-m 'Summary: "When Doc Ido, a talented cyber-physician, finds Gally's head in a junk heap..."'
```

Alternately, single quotes can be submitted to yaml by doubling them. The term you're going to want to search for online is 'escaping' special characters to yaml and that should serve as a general purpose guide for situations like this.

**Comment by nuclearedc** [comment]
Thank you for taking the time to reply.
Using the single quote mark ' seems to have done the trick for the series name containing the colon symbol

Unfortunately, the single quote did not work for the summary with a text that contains apostrophes (Gally's, he's,...).
I will have to do some more research on how to escape special characters.
My current workaround is to use ComiTagger GUI and its Comments field. 
However, manual batch editing is so much faster with comicbox (after the initial learning curve on how to install Python and use packages).
