### ISSUE TITLE
CoverArtist not exported correctly to CIX

### ISSUE THREAD

**Issue by warthan07** [ajslater/comicbox#72]
Thanks for the excellent tagger, I like it far better than comictagger!

I found a small issue today. The tag cover_artist is correctly parsed from the comicbox.yaml scheme, but is not exported correctly to ComicInfo.xml. This is due to a typo in the associated schema ("CoverArist" instead of "CoverArtist"):

https://github.com/ajslater/comicbox/blob/5a428f9549fdee932d0ee430ca045ea3bcaa4493/comicbox/schemas/comicinfo.py#L27

**Comment by ajslater** [comment]
Fixed in [v1.1.5](https://github.com/ajslater/comicbox/releases/tag/v1.1.5)
Thank you!
