### ISSUE TITLE
Feature Request: Overwrite Metadata Option

### ISSUE THREAD

**Issue by reverendj1** [ajslater/comicbox#79]
Hello, I'm currently going through my comic collection and adding series groups and tags. One thing that would be super helpful is if we could append to some metadata fields, instead of overwriting them. This is especially helpful for things like crossovers. For example, given the following series:

```
Batman (2016)
Batman-Spawn War Devil (1994)
Spawn (1992)
```

It would nice if I could do:

```
comicbox --recurse --append -m "series_groups: 'Gotham'" -w cr *Batman*
comicbox --recurse --append -m "series_groups: 'Spawn Universe'" -w cr *Spawn*
```

and have Batman-Spawn War Devil (1994) have both Gotham and Spawn Universe series groups.

**Comment by reverendj1** [comment]
Apparently I was mistaken and that's exactly how it works by default. Sorry. On the flip-side, is there any way to overwrite a tag instead of appending it?

**Comment by ajslater** [comment]
Unfortunately not right now. The procedure would be to delete all the tags and rewrite.

It's a good feature idea though. Keep this issue open to remind me.

**Comment by ajslater** [comment]
[comicbox v1.2.0](https://github.com/ajslater/comicbox/releases/tag/v1.2.0) includes an option to overwrite/replace tags instead of merging them.
